batch_size: 128
per_device_batch_size: 32
gradient_accumulation_steps: 1

learning_rate: 2e-5
weight_decay: 0.01
max_epochs:
n_negative: 50

max_steps: 150000
val_check_interval: 5000

# Regularizer settings
FLOPS:
  lambda_q: 8e-4  # Naver Labs Europe settings
  lambda_p: 6e-4  # Naver Labs Europe settings
  T: 50000

warmup_steps: 6000